import { NextResponse } from "next/server";
import { getRegistrationByCode, updatePaymentLink } from "@/lib/registrations";
import { createRedpayOrder } from "@/lib/redpay";

const PRICING_MAP: Record<string, number> = {
  "Dokter Spesialis Patologi Klinik": 500000,
  "Dokter Spesialis Lainnya": 400000,
  "Dokter Umum": 300000,
  ATLM: 250000,
};

export async function POST(req: Request) {
  try {
    const { code, paymentMethod } = await req.json();

    if (!code || !paymentMethod) {
      return NextResponse.json(
        { message: "Kode registrasi dan metode pembayaran diperlukan." },
        { status: 400 },
      );
    }

    const registration = await getRegistrationByCode(code);
    if (!registration) {
      return NextResponse.json(
        { message: "Registrasi tidak ditemukan." },
        { status: 404 },
      );
    }

    if (registration.status === "paid") {
      return NextResponse.json(
        { message: "Pendaftaran ini sudah dibayar." },
        { status: 400 },
      );
    }

    const amount = PRICING_MAP[registration.profession] || 250000;

    try {
      // Generate a unique transaction ID with a timestamp suffix to avoid
      // Redpay rejecting duplicate merchant_transaction_id on renewal.
      // Format: PATKLIN-2026-XXXX-<hex-timestamp>
      const renewalTxId = `${registration.registration_code}-${Date.now().toString(16).toUpperCase()}`;

      // Create order via Redpay API
      const paymentUrl = await createRedpayOrder(
        registration,
        amount,
        paymentMethod,
        renewalTxId,
      );

      console.log("Payment URL:", paymentUrl);
      // Override default local payment URL with the fresh link generated by Redpay
      await updatePaymentLink(registration.registration_code, paymentUrl);

      return NextResponse.json({
        message: "Link pembayaran berhasil dibuat",
        paymentUrl: paymentUrl,
      });
    } catch (redpayError: any) {
      console.error(
        "Gagal membuat order Redpay manual:",
        redpayError.message || redpayError,
      );
      return NextResponse.json(
        { message: `Gagal membuat tagihan: ${redpayError.message}` },
        { status: 400 },
      );
    }
  } catch (error) {
    console.error(error);
    return NextResponse.json(
      { message: "Terjadi kesalahan sistem saat membuat tagihan." },
      { status: 500 },
    );
  }
}
